
import canvasationgroupform.Circle;
import canvasationgroupform.Shape;
import canvasationgroupform.Square;
import canvasationgroupform.Text;
import canvasationgroupform.TextBrushListener;
import java.awt.AWTException;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.Robot;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import java.util.Stack;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author christian_white
 */

public class FrontEnd extends javax.swing.JFrame {
    /**
     * Creates new form FrontEnd
     */
    
//START GUI LOGIC VARIABLES AND REFERENCES
    
    Shape s = new Circle();
    Color brushColor = Color.BLACK;
    Stack<Graphics> frames = new Stack();
    TextBrushListener tbl = new TextBrushListener();
    ArrayList<BufferedImage> history = new ArrayList<>();
    BufferedImage submitted = null;
    
//END GUI LOGIC VARIABLES AND REFERENCES
 
//START AUTOMATED INITIALIZATION BY NETBEANS GUI BUILDER
    
    public FrontEnd() {
        initComponents();
        DrawPanel.addMouseListener(tbl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        DrawPanel = new javax.swing.JPanel();
        HistoryScrollPane = new javax.swing.JScrollPane();
        HistoryContainer = new javax.swing.JPanel();
        ToolPanel = new javax.swing.JPanel();
        BrushSizeSlider = new javax.swing.JSlider();
        CircleBrushButton = new javax.swing.JButton();
        SquareBrushButton = new javax.swing.JButton();
        TextButton = new javax.swing.JButton();
        SubmitButton = new javax.swing.JButton();
        UndoButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        ColorSelectorButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Canvasation");
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        MainPanel.setBackground(new java.awt.Color(0, 0, 0));

        DrawPanel.setBackground(new java.awt.Color(255, 255, 255));
        DrawPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        DrawPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        DrawPanel.setName(""); // NOI18N
        DrawPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                DrawPanelMouseDragged(evt);
            }
        });
        DrawPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                DrawPanelMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DrawPanelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout DrawPanelLayout = new javax.swing.GroupLayout(DrawPanel);
        DrawPanel.setLayout(DrawPanelLayout);
        DrawPanelLayout.setHorizontalGroup(
            DrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );
        DrawPanelLayout.setVerticalGroup(
            DrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 156, Short.MAX_VALUE)
        );

        HistoryScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        HistoryContainer.setBackground(new java.awt.Color(255, 255, 255));
        HistoryContainer.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                HistoryContainerComponentAdded(evt);
            }
        });
        HistoryContainer.setLayout(new javax.swing.BoxLayout(HistoryContainer, javax.swing.BoxLayout.Y_AXIS));
        HistoryScrollPane.setViewportView(HistoryContainer);

        ToolPanel.setBackground(new java.awt.Color(255, 255, 255));
        ToolPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tools", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monaco", 0, 12))); // NOI18N

        BrushSizeSlider.setBackground(new java.awt.Color(255, 255, 255));
        BrushSizeSlider.setFont(new java.awt.Font("Monaco", 0, 8)); // NOI18N
        BrushSizeSlider.setMajorTickSpacing(5);
        BrushSizeSlider.setMaximum(50);
        BrushSizeSlider.setPaintLabels(true);
        BrushSizeSlider.setValue(10);

        CircleBrushButton.setText("Circle");
        CircleBrushButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CircleBrushButtonActionPerformed(evt);
            }
        });

        SquareBrushButton.setText("Square");
        SquareBrushButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SquareBrushButtonActionPerformed(evt);
            }
        });

        TextButton.setText("Text");
        TextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ToolPanelLayout = new javax.swing.GroupLayout(ToolPanel);
        ToolPanel.setLayout(ToolPanelLayout);
        ToolPanelLayout.setHorizontalGroup(
            ToolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BrushSizeSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ToolPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CircleBrushButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SquareBrushButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ToolPanelLayout.setVerticalGroup(
            ToolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ToolPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ToolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CircleBrushButton)
                    .addComponent(SquareBrushButton)
                    .addComponent(TextButton))
                .addGap(18, 18, 18)
                .addComponent(BrushSizeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        SubmitButton.setBackground(new java.awt.Color(255, 255, 255));
        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        UndoButton.setText("Undo");
        UndoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UndoButtonActionPerformed(evt);
            }
        });

        ClearButton.setText("Clear");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        ColorSelectorButton.setText("Color");

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(DrawPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ColorSelectorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UndoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SubmitButton))
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addComponent(ToolPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HistoryScrollPane))
                .addContainerGap())
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HistoryScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ToolPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DrawPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(SubmitButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UndoButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ClearButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ColorSelectorButton)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//END AUTOMATED INITIALIZATION BY NETBEANS GUI BUILDER
    
//START LISTENERS
    private void DrawPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DrawPanelMouseReleased
        frames.push(DrawPanel.getGraphics());
        System.out.println("Frames in stack: " + frames.size());
    }//GEN-LAST:event_DrawPanelMouseReleased

    private void DrawPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DrawPanelMouseDragged
        draw(evt, BrushSizeSlider.getValue());
    }//GEN-LAST:event_DrawPanelMouseDragged

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void DrawPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DrawPanelMouseClicked
        draw(evt, BrushSizeSlider.getValue());
    }//GEN-LAST:event_DrawPanelMouseClicked

    private void CircleBrushButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CircleBrushButtonActionPerformed
        s = new Circle();
    }//GEN-LAST:event_CircleBrushButtonActionPerformed

    private void SquareBrushButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SquareBrushButtonActionPerformed
        s = new Square();
    }//GEN-LAST:event_SquareBrushButtonActionPerformed

    private void TextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextButtonActionPerformed
        s = new Text("Hello world!");
    }//GEN-LAST:event_TextButtonActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        submitted = convertToBI(DrawPanel);
        HistoryContainer.add(new JLabel(new ImageIcon(submitted)));
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void HistoryContainerComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_HistoryContainerComponentAdded
        evt.getChild().setVisible(true);
        evt.getContainer().revalidate();
        evt.getContainer().repaint();
    }//GEN-LAST:event_HistoryContainerComponentAdded

    private void UndoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UndoButtonActionPerformed

    }//GEN-LAST:event_UndoButtonActionPerformed
    
//END LISTENERS
    
//START CUSTOM/HELPER METHODS
    /**
     * 
     * @param canDraw: boolean switch 
     * @param evt
     * @param s 
     */
    private void draw(MouseEvent evt, int size){        
            DrawPanel.getGraphics().setColor(Color.BLACK);
            s.draw(DrawPanel.getGraphics(), evt.getPoint(), size);
    }
    
    /**
     * Converts the panel into a BufferedImage
     * to be displayed in the HistoryScrollPane and stored in Firebase
     * @param panel: panel to be converted to a BufferedImage
     * @return: BufferedImage of user's drawing to be sent
     */
    private BufferedImage convertToBI(JPanel panel){
    //Get top-left coordinate of drawPanel w/ respect to screen
    Point p = panel.getLocationOnScreen();
    
    //Get the region with width and height of panel and 
    // starting coordinates of p.x and p.y
    Rectangle region = panel.getBounds();
    region.x = p.x;
    region.y = p.y;

    //Get screen capture over the area of region
    BufferedImage bi = null;
    try {
        bi = new Robot().createScreenCapture( region );
    } catch (AWTException ex) {
        Logger.getLogger(FrontEnd.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    return bi;
    }
   
//END CUSTOM/HELPER METHODS
    
//START MAIN
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrontEnd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrontEnd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrontEnd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrontEnd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrontEnd().setVisible(true);
            }
        });
    }
    
//END MAIN
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider BrushSizeSlider;
    private javax.swing.JButton CircleBrushButton;
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton ColorSelectorButton;
    private javax.swing.JPanel DrawPanel;
    private javax.swing.JPanel HistoryContainer;
    private javax.swing.JScrollPane HistoryScrollPane;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton SquareBrushButton;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JButton TextButton;
    private javax.swing.JPanel ToolPanel;
    private javax.swing.JButton UndoButton;
    // End of variables declaration//GEN-END:variables
    
}
